# Generated by Django 3.1.5 on 2021-02-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='dbname',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connection',
            name='host',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connection',
            name='password',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connection',
            name='port',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connection',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connection',
            name='username',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
