# Generated by Django 3.1.5 on 2021-02-08 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0003_auto_20210208_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.AddField(
            model_name='connection',
            name='engine',
            field=models.CharField(default='postgres', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('user', 'name')},
        ),
    ]
