# Generated by Django 3.1.5 on 2021-02-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20210208_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='FsQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('vars', models.JSONField()),
                ('raw_sql', models.TextField()),
                ('verify', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fsquery',
            },
        ),
    ]
