# Generated by Django 3.1.5 on 2021-02-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_fsquery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FsQuery',
            new_name='Query',
        ),
        migrations.AlterModelTable(
            name='query',
            table='query',
        ),
    ]
