# Generated by Django 3.1.5 on 2021-02-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20210208_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='engine',
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.connection')),
            ],
            options={
                'verbose_name': 'Engine',
                'verbose_name_plural': 'Engines',
                'db_table': 'engines',
            },
        ),
    ]
