# Generated by Django 3.1.5 on 2021-02-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20210209_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='connection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.connection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engine',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
