# Generated by Django 3.1.5 on 2021-02-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20210210_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='name',
        ),
        migrations.AddField(
            model_name='engine',
            name='engine',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
