# Generated by Django 3.1.5 on 2021-02-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20210210_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='engine',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='connection',
        ),
        migrations.AddField(
            model_name='connection',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.engine'),
        ),
    ]
