# Generated by Django 3.1.5 on 2021-02-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20210210_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='engine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.engine'),
            preserve_default=False,
        ),
    ]
