# Generated by Django 3.1.5 on 2021-02-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20210210_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='dbname',
        ),
        migrations.RemoveField(
            model_name='query',
            name='name',
        ),
        migrations.AlterField(
            model_name='connection',
            name='engine',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
    ]
