# Generated by Django 3.1.5 on 2021-02-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20210210_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='dbname',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
