# Generated by Django 3.1.5 on 2021-02-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_connection_dbname'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
