# Generated by Django 3.1.5 on 2021-02-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_query_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.connection'),
        ),
    ]
