# Generated by Django 3.1.5 on 2021-02-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_query_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='connection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.connection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
