# Generated by Django 3.1.5 on 2021-03-17 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20210224_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(max_length=256)),
                ('chart_type', models.CharField(max_length=256)),
                ('data', models.JSONField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='db.query')),
            ],
            options={
                'verbose_name': 'Charts',
                'verbose_name_plural': 'Charts',
                'db_table': 'charts',
            },
        ),
    ]
