# Generated by Django 3.1.5 on 2021-04-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_teaminvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='user',
            field=models.CharField(max_length=256),
        ),
    ]
