# Generated by Django 3.1.5 on 2021-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_auto_20210419_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='token',
            field=models.CharField(max_length=1000),
        ),
    ]
