# Generated by Django 3.1.5 on 2021-04-20 03:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0024_auto_20210419_1912'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammembers',
            unique_together={('user', 'team')},
        ),
    ]
