# Generated by Django 3.1.5 on 2021-04-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
