# Generated by Django 3.1.5 on 2021-04-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_auto_20210426_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='cron_expression',
        ),
    ]
