# Generated by Django 3.1.5 on 2021-04-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_remove_trigger_cron_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='cron_expression',
            field=models.JSONField(default={}),
        ),
    ]
