# Generated by Django 3.1.5 on 2021-04-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('db', '0030_trigger_cron_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='periodic_task',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
            preserve_default=False,
        ),
    ]
