# Generated by Django 3.1.5 on 2021-04-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='charts',
            new_name='chart',
        ),
    ]
