# Generated by Django 3.1.5 on 2021-04-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareDashBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('dashboard_name', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'ShareDashBoard',
                'verbose_name_plural': 'ShareDashBoards',
                'db_table': 'sharedashBoard',
            },
        ),
    ]
