# Generated by Django 3.1.5 on 2021-04-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0036_sharedashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='chart',
        ),
    ]
