# Generated by Django 3.1.5 on 2021-04-29 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_remove_dashboard_chart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('name', 'project')},
        ),
        migrations.CreateModel(
            name='DashBoardCharts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.charts')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.dashboard')),
            ],
            options={
                'verbose_name': 'DashBoardCharts',
                'verbose_name_plural': 'DashBoardCharts',
                'db_table': 'dashboardCharts',
            },
        ),
    ]
