# Generated by Django 3.1.5 on 2021-04-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_auto_20210429_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedashboard',
            name='dashboard_name',
        ),
        migrations.AddField(
            model_name='sharedashboard',
            name='dashboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.dashboard'),
            preserve_default=False,
        ),
    ]
