# Generated by Django 3.1.5 on 2021-04-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_auto_20210429_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='cron_expression',
            field=models.JSONField(default=dict),
        ),
    ]
