# Generated by Django 3.1.5 on 2021-05-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_userpasswordresettokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='charts',
            name='height',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='charts',
            name='position_x',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='charts',
            name='position_y',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='charts',
            name='width',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
