# Generated by Django 3.1.5 on 2021-05-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_auto_20210504_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charts',
            name='height',
        ),
        migrations.RemoveField(
            model_name='charts',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='charts',
            name='position_y',
        ),
        migrations.RemoveField(
            model_name='charts',
            name='width',
        ),
        migrations.AddField(
            model_name='dashboardcharts',
            name='height',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dashboardcharts',
            name='position_x',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dashboardcharts',
            name='position_y',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dashboardcharts',
            name='width',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
