# Generated by Django 3.1.5 on 2021-05-04 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0043_auto_20210504_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='charts',
            name='project',
            field=models.ForeignKey(default=109, on_delete=django.db.models.deletion.CASCADE, to='db.project'),
            preserve_default=False,
        ),
    ]
