# Generated by Django 3.1.5 on 2021-05-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0044_charts_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='charts',
            unique_together={('project', 'name')},
        ),
    ]
