# Generated by Django 3.1.5 on 2021-05-07 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_datamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='project',
            field=models.ForeignKey(default=109, on_delete=django.db.models.deletion.CASCADE, to='db.project'),
            preserve_default=False,
        ),
    ]
