# Generated by Django 3.1.5 on 2021-05-10 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0047_trigger_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='charts',
            name='save_from',
            field=models.CharField(default='query', max_length=256),
        ),
        migrations.CreateModel(
            name='DataModelCharts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(max_length=256)),
                ('chart_type', models.CharField(max_length=256)),
                ('save_from', models.CharField(default='data_model', max_length=256)),
                ('data', models.JSONField()),
                ('data_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.datamodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DataModelCharts',
                'verbose_name_plural': 'DataModelCharts',
                'db_table': 'datamodelcharts',
                'unique_together': {('project', 'name')},
            },
        ),
    ]
