# Generated by Django 3.1.5 on 2021-05-14 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0048_auto_20210510_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='charts',
            name='data_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.datamodel'),
        ),
        migrations.AlterField(
            model_name='charts',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.query'),
        ),
    ]
