# Generated by Django 3.1.5 on 2021-05-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0049_auto_20210514_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charts',
            name='save_from',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
