# Generated by Django 3.1.5 on 2021-05-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0051_auto_20210514_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
