# Generated by Django 3.1.5 on 2021-05-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0052_trigger_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
