# Generated by Django 3.1.5 on 2021-05-17 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0053_dashboard_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('data', models.JSONField(default=dict)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.trigger')),
            ],
            options={
                'verbose_name': 'TriggerOutput',
                'verbose_name_plural': 'TriggerOutputs',
                'db_table': 'triggeroutputs',
            },
        ),
    ]
