# Generated by Django 3.1.5 on 2021-05-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0054_triggeroutput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataModelCharts',
        ),
    ]
