# Generated by Django 3.1.5 on 2021-05-19 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('db', '0055_delete_datamodelcharts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cron_expression', models.JSONField(default=dict)),
                ('timezone', models.CharField(max_length=256)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.charts')),
                ('periodic_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project')),
            ],
            options={
                'verbose_name': 'ChartTrigger',
                'verbose_name_plural': 'ChartTriggers',
                'db_table': 'charttriggers',
            },
        ),
    ]
