# Generated by Django 3.1.5 on 2021-05-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0056_charttrigger'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='charttrigger',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='trigger',
            unique_together={('project', 'name')},
        ),
    ]
