# Generated by Django 3.1.5 on 2021-05-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0057_auto_20210520_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charttrigger',
            name='periodic_task',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='periodic_task',
        ),
    ]
