# Generated by Django 3.1.5 on 2021-05-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0058_auto_20210520_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='charts',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charttrigger',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardcharts',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmembers',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedashboard',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triggeroutput',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpasswordresettokens',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
