# Generated by Django 3.1.5 on 2021-05-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0059_auto_20210521_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charttrigger',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='email',
        ),
    ]
