# Generated by Django 3.1.5 on 2021-05-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0060_auto_20210521_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='charttrigger',
            name='email',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trigger',
            name='email',
            field=models.JSONField(default=list),
        ),
    ]
