# Generated by Django 3.1.5 on 2021-05-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0061_auto_20210521_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareCharts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('token', models.CharField(max_length=256)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('charts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.charts')),
            ],
            options={
                'verbose_name': 'ShareChart',
                'verbose_name_plural': 'ShareCharts',
                'db_table': 'sharecharts',
            },
        ),
    ]
