# Generated by Django 3.1.5 on 2021-05-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0062_sharecharts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
