# Generated by Django 3.1.5 on 2021-05-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0063_auto_20210525_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ('name',), 'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
    ]
