# Generated by Django 3.1.5 on 2021-07-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0065_exceldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='charttriggers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.charttrigger'),
            preserve_default=False,
        ),
    ]
