# Generated by Django 3.1.5 on 2021-07-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0066_trigger_charttriggers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='charttriggers',
            new_name='charttrigger',
        ),
    ]
