# Generated by Django 3.1.5 on 2021-07-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0067_auto_20210704_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('internal', 'internal'), ('external', 'external')], max_length=256, null=True),
        ),
    ]
