# Generated by Django 3.1.5 on 2021-07-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0068_connection_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.project'),
        ),
    ]
