# Generated by Django 3.1.5 on 2021-07-15 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0069_exceldata_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.connection'),
        ),
    ]
