# Generated by Django 3.1.5 on 2021-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0070_exceldata_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('INTERNAL', 'internal'), ('EXTERNAL', 'external')], max_length=256, null=True),
        ),
    ]
