# Generated by Django 3.1.5 on 2021-07-22 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0071_auto_20210715_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='excel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.exceldata'),
        ),
    ]
