# Generated by Django 3.1.5 on 2021-09-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0072_query_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='account',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='schema',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='warehouse',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('internal', 'internal'), ('external', 'external'), ('snowflake', 'snowflake')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='engine',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='host',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='port',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
