# Generated by Django 3.1.5 on 2021-09-15 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0074_jsondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBigQueryCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('credential_path', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GoogleBigQueryCredential',
                'verbose_name_plural': 'GoogleBigQueryCredentials',
                'db_table': 'GoogleBigQueryCredentials',
            },
        ),
    ]
