# Generated by Django 3.1.5 on 2021-09-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0075_googlebigquerycredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlebigquerycredential',
            name='file_name',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
