# Generated by Django 3.1.5 on 2021-09-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0077_mediaasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlebigquerycredential',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='googlebigquerycredential',
            name='credential_path',
            field=models.URLField(),
        ),
    ]
