# Generated by Django 3.1.5 on 2021-09-21 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0078_auto_20210915_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlebigquerycredential',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.connection'),
        ),
    ]
