# Generated by Django 3.1.5 on 2021-09-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0079_googlebigquerycredential_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('internal', 'internal'), ('external', 'external'), ('snowflake', 'snowflake'), ('bigquery', 'bigquery')], max_length=256, null=True),
        ),
    ]
