# Generated by Django 3.1.5 on 2021-09-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0080_auto_20210921_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='dbname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
