# Generated by Django 3.1.5 on 2021-10-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0082_remove_googlebigquerycredential_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='access',
            field=models.CharField(choices=[('READ', 'read'), ('WRITE', 'write')], default='READ', max_length=256),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('INTERNAL', 'internal'), ('EXTERNAL', 'external'), ('SNOWFLAKE', 'snowflake')], max_length=256, null=True),
        ),
    ]
