# Generated by Django 3.1.5 on 2021-10-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0083_auto_20211010_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinvitation',
            old_name='user',
            new_name='invitee',
        ),
    ]
