# Generated by Django 3.1.5 on 2021-11-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0084_auto_20211013_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
