# Generated by Django 3.1.5 on 2021-12-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0086_charttrigger_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='created_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
