# Generated by Django 3.1.5 on 2022-01-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0089_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='engine_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
