# Generated by Django 3.1.5 on 2022-01-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0091_auto_20220118_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='file_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
