# Generated by Django 3.1.5 on 2022-01-19 04:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0092_exceldata_file_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exceldata',
            unique_together={('user', 'tablename', 'file_type')},
        ),
    ]
