# Generated by Django 3.1.5 on 2022-01-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0093_auto_20220118_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('full_name', models.CharField(max_length=256)),
                ('contact_number', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'ContactSale',
                'verbose_name_plural': 'ContactSales',
                'db_table': 'contactsales',
            },
        ),
    ]
