# Generated by Django 3.1.5 on 2022-02-02 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0095_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsale',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contactsale',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='contactsale',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactsale',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contactsale',
            name='role',
        ),
        migrations.AddField(
            model_name='contactsale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
