# Generated by Django 3.1.5 on 2022-02-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0096_auto_20220202_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
