# Generated by Django 3.1.5 on 2022-03-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0097_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extended_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
