# Generated by Django 3.1.5 on 2022-03-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0098_profile_extended_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModelMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('skiped', models.BooleanField()),
                ('pre_processing', models.JSONField(default=dict)),
                ('modeling_type', models.CharField(choices=[('classification_modeling', 'classification_modeling'), ('regression_modeling', 'regression_modeling')], max_length=256)),
                ('algorithms', models.JSONField(default=list)),
                ('target_variable', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True, null=True)),
                ('data_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.datamodel')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.query')),
            ],
            options={
                'verbose_name': 'DataModelMetaData',
                'verbose_name_plural': 'DataModelMetaData',
                'db_table': 'datamodelmetadata',
            },
        ),
    ]
