# Generated by Django 3.1.5 on 2022-03-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0099_datamodelmetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodelmetadata',
            name='data_model',
        ),
        migrations.RemoveField(
            model_name='datamodelmetadata',
            name='skiped',
        ),
        migrations.AddField(
            model_name='datamodelmetadata',
            name='name',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datamodelmetadata',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datamodelmetadata',
            name='modeling_type',
            field=models.CharField(choices=[('classification', 'classification'), ('regression', 'regression')], max_length=256),
        ),
    ]
