# Generated by Django 3.1.5 on 2022-03-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0100_auto_20220324_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodelmetadata',
            name='url',
        ),
    ]
