# Generated by Django 3.1.5 on 2022-03-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0101_remove_datamodelmetadata_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='meta_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.datamodelmetadata'),
            preserve_default=False,
        ),
    ]
