# Generated by Django 3.1.5 on 2022-03-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0102_datamodel_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='pickle_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
