# Generated by Django 3.1.5 on 2022-03-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0103_datamodel_pickle_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='scaler_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
