# Generated by Django 3.1.5 on 2022-04-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0104_datamodel_scaler_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='json',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.jsondata'),
        ),
        migrations.AlterField(
            model_name='datamodelmetadata',
            name='modeling_type',
            field=models.CharField(choices=[('classification', 'classification'), ('regression', 'regression'), ('timeseries', 'timeseries')], max_length=256),
        ),
    ]
