# Generated by Django 3.1.5 on 2022-07-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0105_auto_20220411_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='module_access',
            field=models.JSONField(choices=[('DATA_SOURCES', 'data_sources'), ('QUERIES', 'queries'), ('MODELS', 'models'), ('CHARTS', 'charts'), ('TRIGGERS', 'triggers'), ('DASHBOARDS', 'dashboards'), ('MEMBERS', 'members')], default=[], max_length=256),
        ),
    ]
