# Generated by Django 3.1.5 on 2022-07-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0106_projectinvitation_module_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvitation',
            name='module_access',
            field=models.JSONField(default=[]),
        ),
    ]
