# Generated by Django 3.1.5 on 2022-07-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0107_auto_20220725_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvitation',
            name='module_access',
            field=models.JSONField(default=list),
        ),
    ]
